---
- name: Cargar lista de usuarios
  include_vars: 
    file: users.yaml

- name: Crear grupos
  group:
    name: "{{ item }}"
  loop: "{{ groups }}"

- name: Crear usuarios
  user:
    name: "{{ item.nombre }}"
    groups: "{{ item.grupos}}"
    password: "{{ item.contra }}"
  loop: "{{ users }}"